source "https://api.berkshelf.com"

metadata

cookbook 'elasticsearch', git: 'https://github.com/elasticsearch/cookbook-elasticsearch.git'
cookbook 'python', git: 'https://github.com/poise/python.git'
cookbook 'build-essential'
cookbook 'yum'
