source "https://api.berkshelf.com"

metadata

cookbook 'elasticsearch', git: 'https://github.com/elasticsearch/cookbook-elasticsearch.git'
cookbook 'td-agent', git: 'https://github.com/treasure-data/chef-td-agent.git'
cookbook 'kibana', git: 'https://github.com/lusis/chef-kibana'
cookbook 'apache2'
cookbook 'php'
cookbook 'ruby_build'
