name             'logging-introduction-case01'
maintainer       ''
maintainer_email ''
license          ''
description      'Installs/Configures '
long_description 'Installs/Configures '
version          '0.1.0'
depends          'php'
depends          'apache'
depends          'java'
depends          'td-agent'
depends          'elasticsearch'
depends          'kibana'
depends          'build-essential'
