# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.5.0"

script = <<SCRIPT
echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.provision "shell", inline: script

  config.vm.box = "chef/centos-6.5"

  config.omnibus.chef_version = "11.8.0"

  config.berkshelf.enabled = true

  config.vm.define :host1 do | host1 |
    host1.vm.hostname = "app"
    host1.vm.network :private_network, ip: "192.168.33.10"
    host1.vm.provision :chef_solo do |chef|
      chef_gem_path    = "/opt/chef/embedded/lib/ruby/gems/1.9.1"
      chef.binary_env  = "GEM_PATH=#{chef_gem_path} GEM_HOME=#{chef_gem_path}"
      chef.binary_path = "/opt/chef/bin"

      chef.run_list = %w[
        recipe[logging-introduction-case01::default]
        recipe[logging-introduction-case01::rvm]
        recipe[logging-introduction-case01::rvm_config]
        recipe[logging-introduction-case01::app]
        recipe[logging-introduction-case01::app_config]
        recipe[logging-introduction-case01::td-agent]
        recipe[logging-introduction-case01::fluentd-ui]
        recipe[logging-introduction-case01::fluentd_config]
      ]

=begin
      chef.run_list = %w[
        recipe[logging-introduction-case01::default]
        recipe[logging-introduction-case01::rvm]
        recipe[logging-introduction-case01::rvm_config]
        recipe[logging-introduction-case01::app]
        recipe[logging-introduction-case01::app_config]
        recipe[logging-introduction-case01::td-agent]
        recipe[logging-introduction-case01::fluentd-ui]
        recipe[logging-introduction-case01::fluentd_config]
      ]
=end
    end
  end

  config.vm.define :host2 do | host2 |
    host2.vm.hostname = "logging"
    host2.vm.network :private_network, ip: "192.168.33.20"
    host2.vm.provision :chef_solo do |chef|
      chef_gem_path    = "/opt/chef/embedded/lib/ruby/gems/1.9.1"
      chef.binary_env  = "GEM_PATH=#{chef_gem_path} GEM_HOME=#{chef_gem_path}"
      chef.binary_path = "/opt/chef/bin"

      chef.run_list = %w[
        recipe[logging-introduction-case01::default]
        recipe[logging-introduction-case01::elasticsearch]
        recipe[logging-introduction-case01::kibana]
      ]
    end
  end
end
