name             'logging-introduction-case02'
maintainer       'YOUR_COMPANY_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures case02'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'td-agent'
depends          'yum'
depends          'yum-epel'
depends          'rvm'
depends          'apache2'
depends          'mysql'
