source "https://api.berkshelf.com"

metadata

cookbook 'elasticsearch', git: 'https://github.com/elasticsearch/cookbook-elasticsearch.git'
cookbook 'kibana', git: 'https://github.com/lusis/chef-kibana.git'
cookbook 'apache2'
cookbook 'rvm', github: 'fnichol/chef-rvm'
