name             'logging-introduction-case04'
maintainer       'YOUR_COMPANY_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures case04'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'apache'
depends          'java'
depends          'elasticsearch'
depends          'kibana'
depends          'rvm'
depends          'yum-epel'
