# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.5.0"

script = <<SCRIPT
echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.provision "shell", inline: script

  config.vm.box = "chef/centos-6.5"

  config.omnibus.chef_version = :latest

  config.berkshelf.enabled = true

  config.vm.define :host1 do | host1 |
    host1.vm.hostname = "case01"
    host1.vm.network :private_network, ip: "192.168.33.10"
    host1.vm.provision :chef_solo do |chef|
      chef.run_list = %w[
        recipe[logging-introduction-case03::default]
        recipe[logging-introduction-case03::base]
      ]
    end
  end
end
